# Generated by Django 5.0.7 on 2024-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='pol',
            field=models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский')], max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
    ]
